version: '3.8'
services:
  # 服务一：Ray头节点，即我们的“单节点集群”
  ray-head:
    # 使用当前目录下的Dockerfile进行构建
    build: .
    # 容器启动后执行的命令
    command: bash -c "ray start --head --dashboard-host=0.0.0.0 && tail -f /dev/null"
    # 端口映射：将我们笔记本的8265端口映射到容器的8265端口，以便访问Ray Dashboard
    ports:
      - "8265:8265"

  # 服务二：我们的Python应用客户端
  ray-client:
    build: .
    # 容器启动后执行的命令：直接运行我们的Python脚本
    command: python main.py
    # 关键：确保在ray-head服务启动之后再启动本服务
    depends_on:
      - ray-head
    # 关键：设置环境变量，告诉脚本Ray集群的地址。
    # "ray-head"是服务名，Docker Compose会将其解析为正确的IP地址。
    environment:
      - RAY_ADDRESS=ray://ray-head:10001